export {Dashboard} from "./dashboard.jsx"
export {Statistics} from "./statistics.jsx"
export {Home} from "./home.jsx"
export {ProductDetails} from "./productDetails.jsx"
export {CategoryProducts} from "./category-products.jsx"